### PR TITLE
Reproducible universal packages

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by lefou** [comment]
@raboof, thank you!

**Comment by raboof** [comment]
(rebased on top of now-building master)

**Comment by raboof** [comment]
Excellent point, I might have missed that, will check later.

**Comment by atooni** [comment]
I have just checked out the fork and built it. All OSGi manifests are still there. 
From my point of view the PR is good to merge !

Thanks for the contribution.

**Pull request merged**
